Criando autenticação com JWT
UnBArqDsw2021-1/2021.1_G02_TaNaMesa_Order_Service pull request #18
Opened 2021-09-22 02:02 UTC by lboaventura25

## Issue 
Resolves #17 

## Descrição
Criando autenticação com JWT.

## Checklist:

- [x] Meu código segue os padrões de estilo desse projeto.
- [ ] Minhas alterações necessitam de atualização na documentação.
- [ ] Eu atualizei a documentação de acordo com as mudanças feitas nesse PR.

## Como validar?
Criar um employee com um password e logar na aplicação no /login com cpf e senha

1. Curl para criar employee no postman ou insomnia:
```
curl --location --request POST 'http://0.0.0.0:3333/employee' \
--header 'Content-Type: application/json' \
--data-raw '{
	"employee": {
		"cpf": "123456",
		"name": "Lucas Tiago",
		"occupation": "garcom",
        "password": "123456"
	}
}'
```

2. Curl para testar o login no postman ou insomnia:
```
curl --location --request POST 'http://0.0.0.0:3333/login' \
--header 'Content-Type: application/json' \
--data-raw '{
    "cpf": "123456",
    "password": "123456"
}'
```

3. Curl para testar bater em um endpoint protegido sem o token no postman ou insomnia:
```
curl --location --request GET 'http://0.0.0.0:3333/item'
```

Você verá a seguinte mensagem:
```
{
    "status": "error",
    "message": "JWT token não existe no header"
}
```

2021-09-25 12:42 UTC, sergiosacj requested changes

2021-09-25 12:42 UTC, sergiosacj commented on docker-compose.yml
> +      - SECRET=BF64B4D1BCD914B1
Seria legal criar um secret no GitHub para isso.

2021-09-27 13:54 UTC, lboaventura25 commented on docker-compose.yml
> +      - SECRET=BF64B4D1BCD914B1
Como faz isso kkkkkk??
Essa secret só está sendo usada em desenvolvimento

2021-09-27 16:50 UTC, sergiosacj commented on docker-compose.yml
> +      - SECRET=BF64B4D1BCD914B1
Criei, o nome dele é POSTGRES_SECRET.

Acredito que você consegue editá-lo [aqui](https://github.com/UnBArqDsw2021-1/2021.1_G02_TaNaMesa_Order_Service/settings/secrets/actions), se precisar.

2021-09-27 17:11 UTC, abner423 commented on docker-compose.yml
> +      - SECRET=BF64B4D1BCD914B1
Mas então precisa alterar mais alguma coisa a nivel de código ?

2021-09-27 23:07 UTC, sergiosacj commented on docker-compose.yml
> +      - SECRET=BF64B4D1BCD914B1
Precisa não, me confundi com os secrets das pipelines.

2021-09-27 23:08 UTC, sergiosacj approved these changes

2021-09-29 02:36 UTC, ServidioEC approved these changes

2021-09-29 21:42 UTC, merged