(#98) Ajustando model de comanda
UnBArqDsw2021-1/2021.1_G02_TaNaMesa_Order_Service pull request #4
Opened 2021-09-06 15:30 UTC by abner423

## Issue 
Resolves https://github.com/UnBArqDsw2021-1/2021.1_G02_TaNaMesa_docs/issues/98

## Descrição
Implementa a model de comanda

## Checklist:
- [ ] Meu código segue os padrões de estilo desse projeto.
- [ ] Os atributos estão em inglês e sem erros ortográficos

## Como validar?
Subir a aplicação e checar no banco de dados se a model foi criada corretamente

2021-09-06 16:49 UTC, emysdias commented on src/models/Order.ts
> +        type: ENUM("na fila", "na cozinha", "preparado", "na mesa"),
Vai ter o status 'pago', ou tiraram?

2021-09-06 17:12 UTC, sergiosacj commented
Onde que está a primeira versão da model que você tinha comentado?

2021-09-06 21:08 UTC, abner423 commented on src/models/Order.ts
> +        type: ENUM("na fila", "na cozinha", "preparado", "na mesa"),
Eu segui o modelo de dados e la realmente não tem
https://unbarqdsw2021-1.github.io/2021.1_G02_TaNaMesa_docs/2-Modelagem/extras/Modelo-Dados/

2021-09-06 23:45 UTC, emysdias approved these changes
Então tudo show
![image](https://user-images.githubusercontent.com/52640974/132266115-52077d7e-ceed-4ce1-8c17-2c3a30e0873b.png)

2021-09-06 23:53 UTC, emysdias commented
pera, os q o tiago fez tem esses aqui
![image](https://user-images.githubusercontent.com/52640974/132266367-be8e5e31-602b-4287-b252-f011eadb5217.png)

ai acho q pra ficar padrão deveria mostrar tbm, os created_at e updated_at

2021-09-06 23:58 UTC, emysdias requested changes
ai deixando com o created_at e updated_at eu aceito

2021-09-08 21:56 UTC, abner423 commented
Coloquei o Created_at e updated_at aproveitando o próprio sequelize, deixando ele gerenciar

2021-09-13 02:40 UTC, emysdias approved these changes
top top 🏆

2021-09-13 12:13 UTC, tsrrodrigues approved these changes

2021-09-13 12:14 UTC, merged

2021-09-13 12:14 UTC, danieldagerom approved these changes