Cria models de Item e Client
UnBArqDsw2021-1/2021.1_G02_TaNaMesa_Order_Service pull request #5
Opened 2021-09-06 20:49 UTC by tsrrodrigues

## Issue 
Resolves [UnBArqDsw2021-1/2021.1_G02_TaNaMesa_docs#98](https://github.com/UnBArqDsw2021-1/2021.1_G02_TaNaMesa_docs/issues/98)

## Descrição
Cria as models de Item e Client

2021-09-06 23:57 UTC, emysdias requested changes
Ficou ótimo, criou todos mas tem q padronizar os atributos, uns estão em português, outros ingles, a gente combinou de deixar tudo ingles. Tipo ao invés de ser id_mesa, ser: id_table

2021-09-06 23:57 UTC, emysdias commented on src/models/Item.ts
> +    "items",
faltou o cpfGerente

2021-09-07 13:52 UTC, lboaventura25 commented
Muito bom! 
@danieldagerom e @tsrrodrigues, a única observação é que será necessário colocar o timestamps em false e criar os campos de createdAt e updateAt manualmente como na imagem abaixo.
![Captura de tela de 2021-09-07 10-51-04](https://user-images.githubusercontent.com/49161615/132356465-465cc9f5-fa4b-477f-96ae-2e556a176cb7.png)

2021-09-12 20:27 UTC, tsrrodrigues commented on src/models/Item.ts
> +    "items",
Foi analisado e o cpfGerente não vai ser necessário, pois não precisamos obrigatoriamente relacionar um item a um gerente.

2021-09-12 20:47 UTC, alvesitalo approved these changes

2021-09-12 20:49 UTC, merged