Criação de CRUDs de Clientes e Itens
UnBArqDsw2021-1/2021.1_G02_TaNaMesa_Order_Service pull request #7
Opened 2021-09-12 21:53 UTC by tsrrodrigues

## Issue 
Resolves #6 

## Descrição
Cria CRUDs de Clientes e Itens. Para facilitar os testes, criamos uma collection do Postman na pasta docs.

## Como validar?
Pegar a collection do Postman e rodar as rotas de CRUD de cada model. Testar as validações de campos e testar filtro category na rota GET /items. ;)

2021-09-13 10:07 UTC, abner423 requested changes
Ficou muito bom, apenas nas models na interface por exemplo ItemAttributes colocar igual na model mesmo. Nessa interface ta em português e na model ta em inglês, acho que tirando isso ta tudo beleza

2021-09-13 11:27 UTC, tsrrodrigues commented
> Ficou muito bom, apenas nas models na interface por exemplo ItemAttributes colocar igual na model mesmo. Nessa interface ta em português e na model ta em inglês, acho que tirando isso ta tudo beleza

Opa, corrigi lá, valeu Abner. Também adicionei o padrão de projeto controlador, se puder dar uma olhada de novo.

2021-09-13 12:17 UTC, brendavsantos approved these changes

2021-09-13 18:28 UTC, abner423 approved these changes
Curti muito, aproveitei e refatorei o meu kkkk. Gostei da ideia do query params ali, parabéns !

2021-09-14 12:07 UTC, herickport approved these changes

2021-09-14 12:10 UTC, merged